{% set name = "foamalgo" %}
{% set version = "0.1.1" %}
{% set sha256 = "d1d2ec70bb48786c5ff22e80cfe6e308cfd450b06347af13c6c4f40d1eb03a0e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zhujun98/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win or py==27]

outputs:
  - name: foamalgo
    script: build_cpp.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
      host:
        - tbb >=2019.9,<2021.0
        - tbb-devel
        - xsimd >=7.6.0
        - xtensor-blas >=0.19.1
      run:
        - tbb
        - tbb-devel
        - {{ pin_compatible('xsimd', max_pin='x.x') }}
        - {{ pin_compatible('xtensor-blas', max_pin='x.x') }}
    test:
      commands:
        - test -d ${PREFIX}/include/foamalgo  # [unix]
        - test -f ${PREFIX}/include/foamalgo/geometry.hpp  # [unix]
        - test -f ${PREFIX}/lib/cmake/foamalgo/foamalgoConfig.cmake  # [unix]
  - name: pyfoamalgo
    script: build_py.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
      host:
        - python
        - pip
        - h5py >=2.10.0
        - numpy >=1.16.1
        - scipy >=1.2.1
        - tbb >=2019.9,<2021.0
        - tbb-devel
        - xsimd >=7.6.0
        - xtensor-blas >=0.19.1
        - xtensor-python >=0.25.3
      run:
        - python
        - h5py
        - numpy
        - scipy
        - tbb
    test:
      imports:
        - pyfoamalgo
        - pyfoamalgo.geometry

about:
  home: https://github.com/zhujun98/foamalgo
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Algorithms for real-time data analysis in accelerator and photon science

  doc_url: https://foamalgo.readthedocs.io/
  dev_url: https://github.com/zhujun98/foamalgo

extra:
  recipe-maintainers:
    - zhujun98
