{% set name = "foamalgo" %}
{% set version = "0.1.2" %}
{% set sha256 = "89e05a4a033c7f3b0d7e59a0a6e3151201be1f67c6d1e2ca60dffa7f7550e687" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zhujun98/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py==27]

outputs:
  - name: foamalgo
    script: build_cpp.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - tbb >=2019.9
        - tbb-devel
        - xsimd >=8.0.5
        - xtensor-blas >=0.20.0
      run:
        - tbb
        - tbb-devel
        - {{ pin_compatible('xsimd', max_pin='x.x') }}
        - {{ pin_compatible('xtensor-blas', max_pin='x.x') }}
    test:
      commands:
        - test -d ${PREFIX}/include/foamalgo  # [unix]
        - test -f ${PREFIX}/include/foamalgo/geometry.hpp  # [unix]
        - test -f ${PREFIX}/lib/cmake/foamalgo/foamalgoConfig.cmake  # [unix]
  - name: pyfoamalgo
    script: build_py.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
      host:
        - python
        - pip
        - h5py >=2.10.0
        - numpy >=1.16.1
        - scipy >=1.2.1
        - tbb >=2019.9
        - tbb-devel
        - xsimd >=8.0.5
        - xtensor-blas >=0.20.0
        - xtensor-python >=0.26.0
      run:
        - python
        - h5py
        - numpy
        - scipy
        - tbb
    test:
      imports:
        - pyfoamalgo
        - pyfoamalgo.geometry

about:
  home: https://github.com/zhujun98/foamalgo
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Algorithms for real-time data analysis in accelerator and photon science

  doc_url: https://foamalgo.readthedocs.io/
  dev_url: https://github.com/zhujun98/foamalgo

extra:
  recipe-maintainers:
    - zhujun98
